name: scarvs
description: A Ecommerce App :) .

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cache_manager: ^1.0.0+3
  concentric_transition: ^1.0.1+1
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.3.1
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  lottie: ^1.2.1
  provider: ^6.0.1
  salomon_bottom_bar: ^3.1.0
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#42a5f5"
  image: assets/splash.png
  android: true
  ios: true
  web: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/shoes/
  fonts:
    - family: Contax
      fonts:
        - asset: assets/fonts/contax.ttf
